ALTER TABLE public.auth_group_permissions
DROP
CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;

ALTER TABLE public.auth_group_permissions
DROP
CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;

ALTER TABLE public.auth_permission
DROP
CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;

ALTER TABLE public.auth_user_groups
DROP
CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id;

ALTER TABLE public.auth_user_groups
DROP
CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;

ALTER TABLE public.auth_user_user_permissions
DROP
CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;

ALTER TABLE public.auth_user_user_permissions
DROP
CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;

ALTER TABLE public.django_admin_log
DROP
CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;

ALTER TABLE public.django_admin_log
DROP
CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id;

ALTER TABLE public.htd_processed_date_ranges
DROP
CONSTRAINT htd_processed_date_r_processing_job_id_2e7275f8_fk_processin;

CREATE TABLE budget_alerts
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    budget_id             BIGINT                                  NOT NULL,
    cif_id                VARCHAR(100)                            NOT NULL,
    alert_type            VARCHAR(30)                             NOT NULL,
    current_spending      DECIMAL(15, 2),
    budget_limit          DECIMAL(15, 2),
    percentage_used       INTEGER,
    category              VARCHAR(100),
    alert_message         TEXT,
    is_sent               BOOLEAN                                 NOT NULL,
    sent_at               TIMESTAMP WITHOUT TIME ZONE,
    notification_channels VARCHAR(100),
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_budget_alerts PRIMARY KEY (id)
);

CREATE TABLE budgets
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cif_id              VARCHAR(100)                            NOT NULL,
    category            VARCHAR(100)                            NOT NULL,
    budget_amount       DECIMAL(15, 2)                          NOT NULL,
    period_type         VARCHAR(20)                             NOT NULL,
    start_date          date                                    NOT NULL,
    end_date            date                                    NOT NULL,
    is_active           BOOLEAN                                 NOT NULL,
    alert_threshold_80  BOOLEAN                                 NOT NULL,
    alert_threshold_100 BOOLEAN                                 NOT NULL,
    rollover_enabled    BOOLEAN,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    CONSTRAINT pk_budgets PRIMARY KEY (id)
);

CREATE TABLE spending_insights
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cif_id                VARCHAR(100)                            NOT NULL,
    insight_type          VARCHAR(50)                             NOT NULL,
    category              VARCHAR(100),
    insight_message       TEXT                                    NOT NULL,
    action_recommendation TEXT,
    potential_savings     DECIMAL(15, 2),
    priority              VARCHAR(20),
    is_read               BOOLEAN                                 NOT NULL,
    is_actioned           BOOLEAN                                 NOT NULL,
    valid_until           TIMESTAMP WITHOUT TIME ZONE,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_spending_insights PRIMARY KEY (id)
);

CREATE INDEX idx_trans_cif_category_date ON public.transactions (cif_id, category, tran_date);

CREATE INDEX idx_trans_cif_date_range ON public.transactions (cif_id, tran_date, pstd_date);

DROP TABLE public.auth_group CASCADE;

DROP TABLE public.auth_group_permissions CASCADE;

DROP TABLE public.auth_permission CASCADE;

DROP TABLE public.auth_user CASCADE;

DROP TABLE public.auth_user_groups CASCADE;

DROP TABLE public.auth_user_user_permissions CASCADE;

DROP TABLE public.django_admin_log CASCADE;

DROP TABLE public.django_content_type CASCADE;

DROP TABLE public.django_migrations CASCADE;

DROP TABLE public.django_q_ormq CASCADE;

DROP TABLE public.django_q_schedule CASCADE;

DROP TABLE public.django_q_task CASCADE;

DROP TABLE public.django_session CASCADE;

DROP TABLE public.dtd_checkpoint CASCADE;

DROP TABLE public.htd_processed_date_ranges CASCADE;

DROP TABLE public.processing_config CASCADE;

DROP TABLE public.processing_jobs CASCADE;

ALTER TABLE public.transactions
    ALTER COLUMN acid DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN category DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN cif_id SET NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN confidence DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE public.transactions
ALTER
COLUMN migration_status TYPE VARCHAR(255) USING (migration_status::VARCHAR(255));

ALTER TABLE public.transactions
    ALTER COLUMN migration_status DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN processed_at DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN source_table DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN subcategory DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN tran_amt DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN tran_date DROP NOT NULL;

ALTER TABLE public.transactions
    ALTER COLUMN tran_id DROP NOT NULL;

ALTER TABLE public.transactions
ALTER
COLUMN user_part_tran_code TYPE VARCHAR(255) USING (user_part_tran_code::VARCHAR(255));